# Generated by Django 3.0 on 2019-12-19 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191218_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singleroom',
            old_name='booked_end',
            new_name='departure_date',
        ),
        migrations.RemoveField(
            model_name='singleroom',
            name='booked_at',
        ),
        migrations.RemoveField(
            model_name='singleroom',
            name='pic',
        ),
        migrations.AddField(
            model_name='singleroom',
            name='arrival_date',
            field=models.DateField(default=datetime.date(2019, 12, 19)),
        ),
        migrations.AlterField(
            model_name='singleroom',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
